name: Haskell CI

on:
  push:
    branches: [ "main" , "test_environment"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
 
    - uses: haskell-actions/setup@v2.7.6
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10.3.0'

    - name: Cache GHC
      uses: actions/cache@v4.1.2
      with:
        path: /usr/local/.ghcup/ghc/9.4.8
        key: ${{ runner.os }}-ghc-9.4.8

    
    - name: Cache Cabal
      uses: actions/cache@v4.1.2
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install hspec-discover
      run: cabal install hspec-discover --overwrite-policy=always
  
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks all
        
    - name: Run tests
      run: cabal test all
