name: HLint

on: [push]

jobs:
  hlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install HLint
      uses: haskell-actions/hlint-setup@v2.4.10
            
    - name: Run HLint
      uses: haskell-actions/hlint-run@v2.4.10
            
